In [1]:
import numpy as np

In [2]:
a = list(range(10))
b = list(range(10,20))
c = list(range(20,30))

In [3]:
print(a)
print(b)
print(c)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [4]:
data = [a,b,c]

In [5]:
data

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]

In [6]:
[sum(i) for i in data]

[45, 145, 245]

In [7]:
sampleData = np.array(data)
sampleData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [8]:
print("Size : ", sampleData.size)
print("Dimension : ", sampleData.ndim)
print("Shape : ", sampleData.shape)
print("dtype : ", sampleData.dtype)
print("flags : \n", sampleData.flags)
print("strides : ", sampleData.strides)

Size :  30
Dimension :  2
Shape :  (3, 10)
dtype :  int32
flags : 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

strides :  (40, 4)


In [9]:
sampleData2 = np.array([[.4,.5,.6],[.4,.5,.6]])

In [10]:
print("Size : ", sampleData2.size)
print("Dimension : ", sampleData2.ndim)
print("Shape : ", sampleData2.shape)
print("dtype : ", sampleData2.dtype)
print("flags :\n", sampleData2.flags)
print("strides : ", sampleData2.strides)

Size :  6
Dimension :  2
Shape :  (2, 3)
dtype :  float64
flags :
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

strides :  (24, 8)


# Transpose

In [11]:
Transpose_sampleData = sampleData.T

In [12]:
Transpose_sampleData

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26],
       [ 7, 17, 27],
       [ 8, 18, 28],
       [ 9, 19, 29]])

In [13]:
print("Size : ", Transpose_sampleData.size)
print("Dimension : ", Transpose_sampleData.ndim)
print("Shape : ", Transpose_sampleData.shape)
print("dtype : ", Transpose_sampleData.dtype)
print("flags : \n", Transpose_sampleData.flags)
print("strides : ", Transpose_sampleData.strides)

Size :  30
Dimension :  2
Shape :  (10, 3)
dtype :  int32
flags : 
   C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

strides :  (4, 40)


# Slicing 

In [14]:
sampleData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [15]:
sampleData[::]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [16]:
sampleData[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [17]:
sampleData[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [18]:
sampleData[1:, 3:5]

array([[13, 14],
       [23, 24]])

In [19]:
sampleData[2][-1]

29

In [20]:
sampleData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
sampleData.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [22]:
print(sampleData[::2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]]


In [23]:
sampleData[::2].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [24]:
sampleData[::2].strides

(80, 4)

In [25]:
print(sampleData[::2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]]


In [26]:
print(sampleData[:,:])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [27]:
sampleData.strides

(40, 4)

In [28]:
print(sampleData[:3,:3])

[[ 0  1  2]
 [10 11 12]
 [20 21 22]]


In [29]:
sampleData[:3,:3].strides

(40, 4)

In [30]:
sampleData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [31]:
sampleData[::2, ::2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28]])

In [32]:
sampleData[::2, ::2].strides

(80, 8)

In [33]:
sampleData[::2, ::2].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [34]:
sampleData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Copy the data

In [35]:
copied = sampleData

In [36]:
copied

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [37]:
copied[1][2] = 555

In [38]:
copied

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11, 555,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [39]:
sampleData

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11, 555,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [40]:
truecopied = sampleData.copy()

In [41]:
truecopied

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11, 555,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [42]:
truecopied[1][2] = 666

In [43]:
truecopied

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11, 666,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [44]:
sampleData

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11, 555,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

# Mathematical Operations (Axis Wise Evaluations)

In [45]:
a = list(range(0,2000))
b = list(range(2000,4000))
c = list(range(4000,6000))
var = [a,b,c]

In [46]:
data = np.array(var)

In [47]:
data

array([[   0,    1,    2, ..., 1997, 1998, 1999],
       [2000, 2001, 2002, ..., 3997, 3998, 3999],
       [4000, 4001, 4002, ..., 5997, 5998, 5999]])

In [48]:
data.shape, data.size

((3, 2000), 6000)

In [49]:
np.sum(data)

17997000

In [50]:
np.sum(data, axis=0)

array([ 6000,  6003,  6006, ..., 11991, 11994, 11997])

In [51]:
np.sum(data, axis=1)

array([1999000, 5999000, 9999000])

In [52]:
np.max(data)

5999

In [53]:
np.max(data, axis=0)

array([4000, 4001, 4002, ..., 5997, 5998, 5999])

In [54]:
np.max(data, axis=1)

array([1999, 3999, 5999])

# Random number / Reshape

In [55]:
randdata = np.random.random(6000)

In [56]:
randdata

array([0.08756164, 0.35096454, 0.91750066, ..., 0.77364636, 0.60028151,
       0.5916416 ])

In [57]:
randdata.size

6000

In [58]:
randdata.shape

(6000,)

In [59]:
matrix = randdata.reshape(200,30)
matrix

array([[0.08756164, 0.35096454, 0.91750066, ..., 0.89692236, 0.21082223,
        0.63642875],
       [0.45970054, 0.22258393, 0.75036087, ..., 0.25362761, 0.51017002,
        0.24888678],
       [0.83541207, 0.28570858, 0.61377399, ..., 0.93624891, 0.36651015,
        0.1207268 ],
       ...,
       [0.42753968, 0.08361301, 0.40379431, ..., 0.03302356, 0.33019962,
        0.17073662],
       [0.00431463, 0.47632111, 0.69048556, ..., 0.36235483, 0.58722209,
        0.29351371],
       [0.66855966, 0.87952734, 0.05229647, ..., 0.77364636, 0.60028151,
        0.5916416 ]])

In [60]:
matrix.shape

(200, 30)

In [61]:
matrix.sum()

3020.508546781486

In [62]:
np.sum(matrix)

3020.508546781486

In [63]:
np.sum(matrix, axis=0).size

30

In [64]:
np.sum(matrix, axis=1).size

200

In [65]:
matrix.sum(axis=0).shape

(30,)

In [66]:
matrix.sum(axis=1).shape

(200,)

# Example1

create a numpy array with random numbers and get the numbers closest to .50 

In [67]:
data = np.random.random(25)
data

array([0.89245574, 0.43504364, 0.65692343, 0.54523044, 0.35446948,
       0.07021244, 0.13481551, 0.33139983, 0.14747022, 0.6132872 ,
       0.04220297, 0.33259244, 0.07390938, 0.24665857, 0.5053627 ,
       0.53281743, 0.05642465, 0.70114091, 0.94196888, 0.2081157 ,
       0.41594026, 0.70858424, 0.71763692, 0.98758091, 0.1491139 ])

In [68]:
data = data.reshape(5,5)
data

array([[0.89245574, 0.43504364, 0.65692343, 0.54523044, 0.35446948],
       [0.07021244, 0.13481551, 0.33139983, 0.14747022, 0.6132872 ],
       [0.04220297, 0.33259244, 0.07390938, 0.24665857, 0.5053627 ],
       [0.53281743, 0.05642465, 0.70114091, 0.94196888, 0.2081157 ],
       [0.41594026, 0.70858424, 0.71763692, 0.98758091, 0.1491139 ]])

In [69]:
data = abs(data-.5)

In [70]:
minindex = np.argmin(data, axis=0)

In [71]:
data[minindex]

array([[0.03281743, 0.44357535, 0.20114091, 0.44196888, 0.2918843 ],
       [0.39245574, 0.06495636, 0.15692343, 0.04523044, 0.14553052],
       [0.39245574, 0.06495636, 0.15692343, 0.04523044, 0.14553052],
       [0.39245574, 0.06495636, 0.15692343, 0.04523044, 0.14553052],
       [0.45779703, 0.16740756, 0.42609062, 0.25334143, 0.0053627 ]])

## Example 2

##### select the top 5 columns on order of highest variance

In [72]:
sampData2=np.random.random(6000)

In [73]:
sampData2=sampData2.reshape(100,60)

In [74]:
varInfo=np.var(sampData2,axis=0)

In [75]:
incOrder=np.argsort(varInfo)

In [76]:
incOrder[-5:]

array([56, 11, 35, 25, 45], dtype=int64)

In [77]:
sampData2[:,incOrder[-5:]]

array([[0.372793  , 0.11644756, 0.23781546, 0.5486463 , 0.91462979],
       [0.99343949, 0.1866027 , 0.8373482 , 0.28576797, 0.74993438],
       [0.31535512, 0.86037588, 0.82201716, 0.86161566, 0.22450659],
       [0.33319089, 0.83504035, 0.71560069, 0.28426727, 0.07139802],
       [0.19807246, 0.42743016, 0.73756451, 0.94176496, 0.44099199],
       [0.96423589, 0.92041769, 0.16768729, 0.57562095, 0.63016592],
       [0.39447391, 0.39835016, 0.68999395, 0.5257637 , 0.23013849],
       [0.85689821, 0.31998217, 0.97035686, 0.15082599, 0.13673621],
       [0.38930766, 0.99788414, 0.04519021, 0.11776775, 0.98262031],
       [0.43142516, 0.9561876 , 0.05661947, 0.71088809, 0.10511811],
       [0.98362096, 0.42737916, 0.49696219, 0.96416766, 0.47970775],
       [0.31681342, 0.09484707, 0.54443459, 0.92898738, 0.07300636],
       [0.44886601, 0.39231504, 0.91382843, 0.04571786, 0.62136732],
       [0.46550231, 0.84973947, 0.71345888, 0.52766227, 0.22195627],
       [0.4286279 , 0.17077172, 0.

# Broadcasting

In [78]:
data = np.random.random(28).reshape(7,4)

In [79]:
data

array([[0.07549905, 0.98917952, 0.3508262 , 0.25729458],
       [0.66017383, 0.60644613, 0.930384  , 0.87589228],
       [0.08252174, 0.14028051, 0.76904232, 0.24845963],
       [0.87006247, 0.24665604, 0.05288934, 0.06026549],
       [0.95824505, 0.05122022, 0.18804784, 0.56001993],
       [0.51152051, 0.06890185, 0.04929527, 0.16023624],
       [0.91398067, 0.21489006, 0.78168623, 0.37383914]])

In [80]:
data + 5

array([[5.07549905, 5.98917952, 5.3508262 , 5.25729458],
       [5.66017383, 5.60644613, 5.930384  , 5.87589228],
       [5.08252174, 5.14028051, 5.76904232, 5.24845963],
       [5.87006247, 5.24665604, 5.05288934, 5.06026549],
       [5.95824505, 5.05122022, 5.18804784, 5.56001993],
       [5.51152051, 5.06890185, 5.04929527, 5.16023624],
       [5.91398067, 5.21489006, 5.78168623, 5.37383914]])

In [81]:
data + np.array([1,2,3,4])

array([[1.07549905, 2.98917952, 3.3508262 , 4.25729458],
       [1.66017383, 2.60644613, 3.930384  , 4.87589228],
       [1.08252174, 2.14028051, 3.76904232, 4.24845963],
       [1.87006247, 2.24665604, 3.05288934, 4.06026549],
       [1.95824505, 2.05122022, 3.18804784, 4.56001993],
       [1.51152051, 2.06890185, 3.04929527, 4.16023624],
       [1.91398067, 2.21489006, 3.78168623, 4.37383914]])

In [82]:
# data + np.array([1,2,3,4,5,6,7])

In [83]:
np.array([[1],[2],[3],[4],[5],[6],[7]]).shape

(7, 1)

In [84]:
data + np.array([[1],[2],[3],[4],[5],[6],[7]])

array([[1.07549905, 1.98917952, 1.3508262 , 1.25729458],
       [2.66017383, 2.60644613, 2.930384  , 2.87589228],
       [3.08252174, 3.14028051, 3.76904232, 3.24845963],
       [4.87006247, 4.24665604, 4.05288934, 4.06026549],
       [5.95824505, 5.05122022, 5.18804784, 5.56001993],
       [6.51152051, 6.06890185, 6.04929527, 6.16023624],
       [7.91398067, 7.21489006, 7.78168623, 7.37383914]])

# Many matrix languages

In [85]:
a = np.array([[1,0],[0,1]])
b = np.array([[1,1],[1,1]])

In [86]:
a

array([[1, 0],
       [0, 1]])

In [87]:
b

array([[1, 1],
       [1, 1]])

In [88]:
a*b

array([[1, 0],
       [0, 1]])

In [89]:
a.dot(b)

array([[1, 1],
       [1, 1]])

In [90]:
np.dot(a,b)

array([[1, 1],
       [1, 1]])

In [91]:
a @ b

array([[1, 1],
       [1, 1]])

# Handy Functions

In [92]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [93]:
type(np.ones((5,5)))

numpy.ndarray

In [94]:
arrayOf1s=np.ones((5,5))

In [95]:
arrayOf1s.dtype

dtype('float64')

In [96]:
np.ones((5,5),dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [97]:
exqualSpacedArray = np.linspace(0,10,30)

In [98]:
exqualSpacedArray

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [99]:
np.exp(exqualSpacedArray)  #e^x

array([1.00000000e+00, 1.41174649e+00, 1.99302816e+00, 2.81365052e+00,
       3.97216126e+00, 5.60768473e+00, 7.91662926e+00, 1.11762736e+01,
       1.57780651e+01, 2.22746281e+01, 3.14461281e+01, 4.43939611e+01,
       6.26730189e+01, 8.84784147e+01, 1.24909092e+02, 1.76339972e+02,
       2.48947338e+02, 3.51450531e+02, 4.96159055e+02, 7.00450807e+02,
       9.88858971e+02, 1.39601819e+03, 1.97082378e+03, 2.78230356e+03,
       3.92790730e+03, 5.54520936e+03, 7.82842987e+03, 1.10517584e+04,
       1.56022812e+04, 2.20264658e+04])

# np.arange

In [100]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [101]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Other useful functions

In [102]:
simpleArray=np.arange(12)

In [103]:
np.exp(simpleArray)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [104]:
np.sum(simpleArray)

66

In [105]:
np.sqrt(simpleArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [106]:
simpleArraySq=np.sqrt(simpleArray)

In [107]:
np.add(simpleArray,simpleArraySq)

array([ 0.        ,  2.        ,  3.41421356,  4.73205081,  6.        ,
        7.23606798,  8.44948974,  9.64575131, 10.82842712, 12.        ,
       13.16227766, 14.31662479])

## What if some non supported operations

In [108]:
def funcArray(x,y):
    return x+y

functionCreatedArray = np.fromfunction(funcArray,(15,4),dtype=int)
functionCreatedArray

array([[ 0,  1,  2,  3],
       [ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14],
       [12, 13, 14, 15],
       [13, 14, 15, 16],
       [14, 15, 16, 17]])

# Flat the array

In [109]:
functionCreatedArray.ravel()

array([ 0,  1,  2,  3,  1,  2,  3,  4,  2,  3,  4,  5,  3,  4,  5,  6,  4,
        5,  6,  7,  5,  6,  7,  8,  6,  7,  8,  9,  7,  8,  9, 10,  8,  9,
       10, 11,  9, 10, 11, 12, 10, 11, 12, 13, 11, 12, 13, 14, 12, 13, 14,
       15, 13, 14, 15, 16, 14, 15, 16, 17])

In [110]:
functionCreatedArray.ndim

2

In [111]:
reshapedArray=functionCreatedArray.reshape((15,4,1))

In [112]:
reshapedArray.shape

(15, 4, 1)

In [113]:
reshapedArray.ravel()

array([ 0,  1,  2,  3,  1,  2,  3,  4,  2,  3,  4,  5,  3,  4,  5,  6,  4,
        5,  6,  7,  5,  6,  7,  8,  6,  7,  8,  9,  7,  8,  9, 10,  8,  9,
       10, 11,  9, 10, 11, 12, 10, 11, 12, 13, 11, 12, 13, 14, 12, 13, 14,
       15, 13, 14, 15, 16, 14, 15, 16, 17])

## Reshape in new form

In [114]:
newArr=np.arange(640)

In [115]:
multiDimArr=newArr.reshape(40,4,4)

In [116]:
newArr.shape

(640,)

In [117]:
multiDimArr.shape

(40, 4, 4)

In [118]:
multiDimArr

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]],

       [[ 64,  65,  66,  67],
        [ 68,  69,  70,  71],
        [ 72,  73,  74,  75],
        [ 76,  77,  78,  79]],

       [[ 80,  81,  82,  83],
        [ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95]],

       [[ 96,  97,  98,  99],
        [100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123],
        [124, 125, 126, 127]],

       [[128, 129, 130, 

In [119]:
multiDimArr.shape

(40, 4, 4)

In [120]:
multiDimArr[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### make it as row vector by inserting an axis along first dimension

In [121]:
newArr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [122]:
newArr[np.newaxis,:]

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [123]:
newArr[np.newaxis,:].shape

(1, 640)

In [124]:
newArr[:,np.newaxis]

array([[  0],
       [  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11],
       [ 12],
       [ 13],
       [ 14],
       [ 15],
       [ 16],
       [ 17],
       [ 18],
       [ 19],
       [ 20],
       [ 21],
       [ 22],
       [ 23],
       [ 24],
       [ 25],
       [ 26],
       [ 27],
       [ 28],
       [ 29],
       [ 30],
       [ 31],
       [ 32],
       [ 33],
       [ 34],
       [ 35],
       [ 36],
       [ 37],
       [ 38],
       [ 39],
       [ 40],
       [ 41],
       [ 42],
       [ 43],
       [ 44],
       [ 45],
       [ 46],
       [ 47],
       [ 48],
       [ 49],
       [ 50],
       [ 51],
       [ 52],
       [ 53],
       [ 54],
       [ 55],
       [ 56],
       [ 57],
       [ 58],
       [ 59],
       [ 60],
       [ 61],
       [ 62],
       [ 63],
       [ 64],
       [ 65],
       [ 66],
       [ 67],
       [ 68],
       [ 69],
       [ 70],
      

In [125]:
newArr[:,np.newaxis].shape

(640, 1)

## Numpy Where

In [126]:
data = np.arange(100,500,50)

In [127]:
data

array([100, 150, 200, 250, 300, 350, 400, 450])

In [128]:
np.where(data<300)

(array([0, 1, 2, 3], dtype=int64),)

In [129]:
data[np.where(data<300)]

array([100, 150, 200, 250])

# Reshape in new form

In [130]:
newarr = np.arange(640)


In [131]:
multidimarr = newarr.reshape(40,4,4)

In [132]:
newarr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [133]:
multidimarr

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]],

       [[ 64,  65,  66,  67],
        [ 68,  69,  70,  71],
        [ 72,  73,  74,  75],
        [ 76,  77,  78,  79]],

       [[ 80,  81,  82,  83],
        [ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95]],

       [[ 96,  97,  98,  99],
        [100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123],
        [124, 125, 126, 127]],

       [[128, 129, 130, 

In [134]:
newarr.shape

(640,)

In [135]:
multidimarr.shape

(40, 4, 4)

In [136]:
multidimarr[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [137]:
newarr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [138]:
newarr.shape

(640,)

In [139]:
newarr[np.newaxis, :]

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [140]:
newarr[np.newaxis, :].shape

(1, 640)

In [141]:
newarr[:, np.newaxis]

array([[  0],
       [  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11],
       [ 12],
       [ 13],
       [ 14],
       [ 15],
       [ 16],
       [ 17],
       [ 18],
       [ 19],
       [ 20],
       [ 21],
       [ 22],
       [ 23],
       [ 24],
       [ 25],
       [ 26],
       [ 27],
       [ 28],
       [ 29],
       [ 30],
       [ 31],
       [ 32],
       [ 33],
       [ 34],
       [ 35],
       [ 36],
       [ 37],
       [ 38],
       [ 39],
       [ 40],
       [ 41],
       [ 42],
       [ 43],
       [ 44],
       [ 45],
       [ 46],
       [ 47],
       [ 48],
       [ 49],
       [ 50],
       [ 51],
       [ 52],
       [ 53],
       [ 54],
       [ 55],
       [ 56],
       [ 57],
       [ 58],
       [ 59],
       [ 60],
       [ 61],
       [ 62],
       [ 63],
       [ 64],
       [ 65],
       [ 66],
       [ 67],
       [ 68],
       [ 69],
       [ 70],
      

In [142]:
newarr[:, np.newaxis].shape

(640, 1)

# Numpy Where

In [143]:
data = np.arange(100,500,50)

In [144]:
data

array([100, 150, 200, 250, 300, 350, 400, 450])

In [145]:
data[np.where(data<300)]   # If we want to find the elements

array([100, 150, 200, 250])

In [146]:
np.where(data<300)   # If we want to find the indices of that elements

(array([0, 1, 2, 3], dtype=int64),)

# Dense layer calculation using numpy

In [147]:
inputLayer = np.random.random(20)

In [148]:
inputLayer

array([0.55367109, 0.93100018, 0.00426138, 0.6743739 , 0.68756467,
       0.91225733, 0.69625569, 0.6597145 , 0.42059174, 0.86266057,
       0.97899025, 0.43046609, 0.16592929, 0.4335217 , 0.20181319,
       0.76194588, 0.3965859 , 0.76984494, 0.74956847, 0.23062463])

In [149]:
hiddenLayer = np.random.randn(500,20)

In [150]:
hiddenLayer

array([[-0.18305839, -0.10131604,  1.04716408, ..., -0.23332295,
        -0.89060042,  0.17098386],
       [ 0.62271932,  0.76956229, -0.99062091, ..., -0.37859671,
        -0.42913941, -0.5266837 ],
       [-0.83977099,  0.69768894, -0.82347971, ...,  0.84271344,
         0.13399914, -0.00270881],
       ...,
       [ 0.0334874 ,  0.67756149, -0.51015983, ...,  0.39493864,
         0.23947925,  0.06282874],
       [-0.27088996, -1.47075276, -0.50324733, ..., -0.03070482,
         0.5569798 ,  0.27687304],
       [-0.52650058,  1.20631368, -0.34215366, ...,  1.46187936,
        -0.86003557, -1.43287188]])

In [151]:
biasLayer = np.random.random(500)

In [152]:
biasLayer

array([0.25522117, 0.91043183, 0.02469266, 0.27849284, 0.6010533 ,
       0.44066556, 0.07746172, 0.53432637, 0.95887778, 0.04549475,
       0.33471685, 0.4679277 , 0.2028443 , 0.36487212, 0.28810759,
       0.253365  , 0.87252374, 0.29854406, 0.07257809, 0.90896293,
       0.736036  , 0.42963302, 0.76880696, 0.23334358, 0.47145623,
       0.90699116, 0.63097012, 0.72138323, 0.50461699, 0.65179095,
       0.34867066, 0.78113954, 0.54178964, 0.08626429, 0.80552692,
       0.46025365, 0.18806089, 0.5814198 , 0.14001873, 0.0590836 ,
       0.44372998, 0.70563795, 0.53755146, 0.13708143, 0.04359087,
       0.55296051, 0.76656873, 0.90333675, 0.20536814, 0.2685346 ,
       0.82476308, 0.89099208, 0.63789968, 0.30493438, 0.54046494,
       0.21711643, 0.11867745, 0.19016795, 0.54011442, 0.67080197,
       0.49867812, 0.34124243, 0.59182544, 0.45402031, 0.70966191,
       0.13301169, 0.48408492, 0.04284681, 0.94655569, 0.75671956,
       0.46958665, 0.12789771, 0.85998061, 0.70178782, 0.58754

In [153]:
inputLayer.shape, hiddenLayer.shape, biasLayer.shape

((20,), (500, 20), (500,))

In [154]:
output = np.dot(hiddenLayer, inputLayer)+biasLayer

In [155]:
output

array([-2.51342216e+00, -2.76343288e+00, -6.23380301e-01, -3.29373284e+00,
       -1.81177811e+00, -3.48939870e+00, -3.66072637e-01, -2.02847775e+00,
        1.22712915e+00,  3.92204173e-01, -1.39781813e+00,  1.61589220e+00,
       -3.16703519e+00,  2.30840508e-01, -5.58842807e+00,  6.67611272e+00,
       -7.65472550e-01, -1.27217015e-01,  1.20073909e+00, -1.00981759e+00,
       -1.96001834e+00,  3.61861352e+00, -1.42484184e+00,  1.49959314e+00,
        1.33080627e+00,  2.59924784e+00,  4.20485515e+00, -1.52981361e+00,
        1.00108432e+00,  1.79412067e+00, -4.37006383e-01, -1.08361492e+00,
        6.80967776e+00,  2.41864184e+00,  6.60198078e+00,  1.64689362e+00,
        6.11904185e-01, -3.70941748e+00,  3.08569744e-01, -5.85442569e+00,
        3.04266815e+00,  2.02322084e+00, -3.26402738e+00, -4.76292051e+00,
       -4.05904761e+00, -6.58971197e-01,  5.80678557e-01, -9.66402447e-01,
       -1.43709746e-01,  2.84460658e+00,  7.16500683e-01,  2.18696932e+00,
       -2.11682733e+00,  

In [156]:
output.shape

(500,)

In [157]:
np.maximum(0,output)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.22712915, 0.39220417,
       0.        , 1.6158922 , 0.        , 0.23084051, 0.        ,
       6.67611272, 0.        , 0.        , 1.20073909, 0.        ,
       0.        , 3.61861352, 0.        , 1.49959314, 1.33080627,
       2.59924784, 4.20485515, 0.        , 1.00108432, 1.79412067,
       0.        , 0.        , 6.80967776, 2.41864184, 6.60198078,
       1.64689362, 0.61190419, 0.        , 0.30856974, 0.        ,
       3.04266815, 2.02322084, 0.        , 0.        , 0.        ,
       0.        , 0.58067856, 0.        , 0.        , 2.84460658,
       0.71650068, 2.18696932, 0.        , 0.33458657, 0.        ,
       5.6653959 , 0.        , 2.77068393, 1.81366844, 6.33368287,
       2.85702451, 0.        , 0.        , 0.        , 0.15206097,
       1.53596839, 0.        , 2.51155029, 0.        , 0.        ,
       0.        , 0.        , 0.59561366, 0.28094911, 0.     

## Convolution layer using Numpy

In [158]:
15*15*3

675

In [159]:
imgdata = np.random.rand(225).reshape(15,15)

In [160]:
imgdata

array([[0.39640502, 0.36378263, 0.47400247, 0.67411203, 0.40915243,
        0.94425486, 0.88607338, 0.13719879, 0.45121919, 0.34065377,
        0.25168473, 0.3752671 , 0.03434507, 0.39702243, 0.86370967],
       [0.06131089, 0.80582712, 0.86496024, 0.84760302, 0.2989075 ,
        0.6671782 , 0.329128  , 0.70597308, 0.17064702, 0.42601306,
        0.17126674, 0.07379921, 0.9150814 , 0.74149466, 0.40545227],
       [0.86132261, 0.96264138, 0.98809337, 0.84105146, 0.44230261,
        0.05849061, 0.93303514, 0.89967575, 0.30487311, 0.60658364,
        0.74626976, 0.43775711, 0.36783773, 0.92582582, 0.6775345 ],
       [0.56875994, 0.84342335, 0.14834925, 0.84331243, 0.6698232 ,
        0.3862112 , 0.31456089, 0.03557041, 0.45458292, 0.25221374,
        0.42681152, 0.69776554, 0.66697562, 0.45096266, 0.18313202],
       [0.54970036, 0.46508254, 0.64894864, 0.37268381, 0.45672684,
        0.87128181, 0.97992338, 0.11613448, 0.70746798, 0.81103157,
        0.32769491, 0.08863533, 0.14167215, 

In [161]:
imgdata.shape

(15, 15)

In [162]:
imgdata[0:3,1:4]

array([[0.36378263, 0.47400247, 0.67411203],
       [0.80582712, 0.86496024, 0.84760302],
       [0.96264138, 0.98809337, 0.84105146]])

In [163]:
imgdata[:5,:5]

array([[0.39640502, 0.36378263, 0.47400247, 0.67411203, 0.40915243],
       [0.06131089, 0.80582712, 0.86496024, 0.84760302, 0.2989075 ],
       [0.86132261, 0.96264138, 0.98809337, 0.84105146, 0.44230261],
       [0.56875994, 0.84342335, 0.14834925, 0.84331243, 0.6698232 ],
       [0.54970036, 0.46508254, 0.64894864, 0.37268381, 0.45672684]])

In [164]:
filtersize = np.array([[1,0,0],[0,1,0],[0,0,1]])

In [165]:
filtersize

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [166]:
for k in range(13):
    for j in range(13):
        print(k,"row", (k,k+3), (j,j+3))

0 row (0, 3) (0, 3)
0 row (0, 3) (1, 4)
0 row (0, 3) (2, 5)
0 row (0, 3) (3, 6)
0 row (0, 3) (4, 7)
0 row (0, 3) (5, 8)
0 row (0, 3) (6, 9)
0 row (0, 3) (7, 10)
0 row (0, 3) (8, 11)
0 row (0, 3) (9, 12)
0 row (0, 3) (10, 13)
0 row (0, 3) (11, 14)
0 row (0, 3) (12, 15)
1 row (1, 4) (0, 3)
1 row (1, 4) (1, 4)
1 row (1, 4) (2, 5)
1 row (1, 4) (3, 6)
1 row (1, 4) (4, 7)
1 row (1, 4) (5, 8)
1 row (1, 4) (6, 9)
1 row (1, 4) (7, 10)
1 row (1, 4) (8, 11)
1 row (1, 4) (9, 12)
1 row (1, 4) (10, 13)
1 row (1, 4) (11, 14)
1 row (1, 4) (12, 15)
2 row (2, 5) (0, 3)
2 row (2, 5) (1, 4)
2 row (2, 5) (2, 5)
2 row (2, 5) (3, 6)
2 row (2, 5) (4, 7)
2 row (2, 5) (5, 8)
2 row (2, 5) (6, 9)
2 row (2, 5) (7, 10)
2 row (2, 5) (8, 11)
2 row (2, 5) (9, 12)
2 row (2, 5) (10, 13)
2 row (2, 5) (11, 14)
2 row (2, 5) (12, 15)
3 row (3, 6) (0, 3)
3 row (3, 6) (1, 4)
3 row (3, 6) (2, 5)
3 row (3, 6) (3, 6)
3 row (3, 6) (4, 7)
3 row (3, 6) (5, 8)
3 row (3, 6) (6, 9)
3 row (3, 6) (7, 10)
3 row (3, 6) (8, 11)
3 row (3, 6

In [167]:
filSize=3
outputVal=[]
for k in range(13):
    for j in range(13):
        sampD=imgdata[k:k+filSize,j:j+filSize]
        outputVal.append(np.sum(sampD*filtersize))
        print (k,'row ',(k,k+3),(j,j+3))

0 row  (0, 3) (0, 3)
0 row  (0, 3) (1, 4)
0 row  (0, 3) (2, 5)
0 row  (0, 3) (3, 6)
0 row  (0, 3) (4, 7)
0 row  (0, 3) (5, 8)
0 row  (0, 3) (6, 9)
0 row  (0, 3) (7, 10)
0 row  (0, 3) (8, 11)
0 row  (0, 3) (9, 12)
0 row  (0, 3) (10, 13)
0 row  (0, 3) (11, 14)
0 row  (0, 3) (12, 15)
1 row  (1, 4) (0, 3)
1 row  (1, 4) (1, 4)
1 row  (1, 4) (2, 5)
1 row  (1, 4) (3, 6)
1 row  (1, 4) (4, 7)
1 row  (1, 4) (5, 8)
1 row  (1, 4) (6, 9)
1 row  (1, 4) (7, 10)
1 row  (1, 4) (8, 11)
1 row  (1, 4) (9, 12)
1 row  (1, 4) (10, 13)
1 row  (1, 4) (11, 14)
1 row  (1, 4) (12, 15)
2 row  (2, 5) (0, 3)
2 row  (2, 5) (1, 4)
2 row  (2, 5) (2, 5)
2 row  (2, 5) (3, 6)
2 row  (2, 5) (4, 7)
2 row  (2, 5) (5, 8)
2 row  (2, 5) (6, 9)
2 row  (2, 5) (7, 10)
2 row  (2, 5) (8, 11)
2 row  (2, 5) (9, 12)
2 row  (2, 5) (10, 13)
2 row  (2, 5) (11, 14)
2 row  (2, 5) (12, 15)
3 row  (3, 6) (0, 3)
3 row  (3, 6) (1, 4)
3 row  (3, 6) (2, 5)
3 row  (3, 6) (3, 6)
3 row  (3, 6) (4, 7)
3 row  (3, 6) (5, 8)
3 row  (3, 6) (6, 9)
3 row  

In [168]:
len(outputVal)

169

In [169]:
outputFinal2=np.array(outputVal).reshape(13,13)

In [170]:
outputFinal2

array([[2.19032551, 2.06979433, 1.76390811, 1.03151014, 2.00936577,
        2.17305862, 1.89691957, 0.91442946, 1.62350201, 0.94967762,
        0.69332168, 2.21617433, 1.45337423],
       [1.17230152, 2.63723292, 2.3758349 , 1.67611683, 0.671959  ,
        1.63578376, 1.68338667, 1.26305993, 1.20404219, 1.87004836,
        1.27599947, 0.8925996 , 2.02403924],
       [2.35369461, 1.48367444, 2.28813264, 2.38215646, 1.80843719,
        0.48918599, 1.67607353, 2.16529023, 0.88478176, 1.1220305 ,
        1.58570745, 2.01839262, 1.49877842],
       [1.7693542 , 2.09280511, 1.43192163, 2.20410287, 2.41194708,
        1.37987084, 0.99593502, 1.67841649, 1.76992799, 0.60775781,
        0.96113583, 1.20500475, 2.11722165],
       [1.24694294, 1.70398586, 1.66884669, 2.02173736, 1.84660645,
        2.02327712, 1.52724998, 1.37018291, 2.6051791 , 2.23163657,
        0.39120532, 0.74808224, 1.07276267],
       [1.49948677, 0.84847398, 1.47169919, 1.48718246, 2.61641854,
        1.45010211, 1.20069

In [171]:
sdata = imgdata[:3,:3]

In [172]:
sdata

array([[0.39640502, 0.36378263, 0.47400247],
       [0.06131089, 0.80582712, 0.86496024],
       [0.86132261, 0.96264138, 0.98809337]])

## Function to try in numpy

 -  np.newaxis
 -  np.matrix
 -  np.tanh	Compute hyperbolic tangent element-wise.
 -  np.arcsinh	Inverse hyperbolic sine element-wise.
 -  np.arccosh	Inverse hyperbolic cosine, element-wise.
 -  np.arctanh	Inverse hyperbolic tangent element-wise.
 -  np.expm1	Calculate exp(x) – 1 for all elements in the array.
 -  np.exp2	Calculate 2**p for all p in the input array.
 -  np.log10	Return the base 10 logarithm of the input array, element-wise.
 -  np.log2	Base-2 logarithm of x.
 -  np.log1p	Return the natural logarithm of one plus the input array, element-wise.
 -  np.logaddexp	Logarithm of the sum of exponentiations of the inputs.
 -  np.logaddexp2	Logarithm of the sum of exponentiations of the inputs in base-2.
 -  np.add	Add arguments element-wise.
 -  np.positive	Numerical positive, element-wise.
 -  np.negative	Numerical negative, element-wise.
 -  np.multiply	Multiply arguments element-wise.
 -  np.power	First array elements raised to powers from second array, element-wise.
 -  np.subtract	Subtract arguments, element-wise.
 -  np.true_divide	Returns a true division of the inputs, element-wise.
 -  np.floor_divide	Return the largest integer smaller or equal to the division of the inputs.
 -  np.float_power	First array elements raised to powers from second array, element-wise.
 -  np.mod	Return the element-wise remainder of division.
 -  np.remainder	Return element-wise remainder of division.
 -  np.divmod	Return element-wise quotient and remainder simultaneously.

source:
 - https://www.youtube.com/watch?v=poD8ud4MxOY
 -      :https://numpy.org/
 -    :https://numpy.org/devdocs/user/quickstart.html