# Numpy

In [1]:
import numpy as np

a = ([[[1,2,3],[4,5,6]],[[2,6,4],[7,8,9]],[[8,2,5],[1,8,6]],[[1,1,4],[9,0,3]]])
arr = np.array(a, dtype = float)
print(arr)

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[2. 6. 4.]
  [7. 8. 9.]]

 [[8. 2. 5.]
  [1. 8. 6.]]

 [[1. 1. 4.]
  [9. 0. 3.]]]


In [2]:
import numpy as np

a = ([[[1,2,3],[4,5,6]],[[2,6,4],[7,8,9]],[[8,2,5],[1,8,6]],[[1,1,4],[9,0,3]]])
arr = np.array(a, dtype = int)
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[2 6 4]
  [7 8 9]]

 [[8 2 5]
  [1 8 6]]

 [[1 1 4]
  [9 0 3]]]


# Zeros

In [3]:
a = np.zeros(2, dtype = int)
print("Matrix a: ", a)

b = np.zeros([2,2], dtype = int)
print("Matrix b: \n", b)

c = np.zeros([3,3])
print("Matrix c: \n", c)


Matrix a:  [0 0]
Matrix b: 
 [[0 0]
 [0 0]]
Matrix c: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Arange and Reshape

In [4]:
array = np.arange(8)
print("Original array: \n", array)

array = np.arange(8).reshape(2,4)
print("Reshaped array with 2 by 4: \n", array)

array = np.arange(8).reshape(4,2)
print("Reshaped array with 4 by 2: \n", array)

array = np.arange(8).reshape(2,2,2)
print("Reshaped array in 3D: \n", array)

Original array: 
 [0 1 2 3 4 5 6 7]
Reshaped array with 2 by 4: 
 [[0 1 2 3]
 [4 5 6 7]]
Reshaped array with 4 by 2: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Reshaped array in 3D: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [5]:
print("A\n", np.arange(4).reshape(2,2), "\n")

print("A\n", np.arange(4,10).reshape(2,3), "\n")

print("A\n", np.arange(4,20,3).reshape(3,2), "\n")

A
 [[0 1]
 [2 3]] 

A
 [[4 5 6]
 [7 8 9]] 

A
 [[ 4  7]
 [10 13]
 [16 19]] 



# linspace

In [6]:
print("B\n", np.linspace(2.0, 3.0, num=5, retstep=True), "\n")

x = np.linspace(0, 2, 10)
print("Value of x\n", x)
print("C\n", np.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

Value of x
 [0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]
C
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


# flatten

In [3]:
import numpy as np
array = np.array([[1,2],[3,4]])

array.flatten()
print(array)

array.flatten('F')
print(array)
print(array.ndim)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
2


# Print Largest Element

In [8]:
arr = np.array([[1,5,6],[4,7,2],[3,1,9]])

print("Largest element is: ", arr.max())

print("Row-wise maximum element: ", arr.max(axis=1))

print("Colume-wise maximum element: ", arr.max(axis=0))

print("Sum of all array element: ", arr.sum())

print("Cumulative sum along each row:\n", arr.cumsum(axis=1))

print("Cumulative sum along each colume:\n", arr.cumsum(axis=0))



Largest element is:  9
Row-wise maximum element:  [6 7 9]
Colume-wise maximum element:  [4 7 9]
Sum of all array element:  38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]
Cumulative sum along each colume:
 [[ 1  5  6]
 [ 5 12  8]
 [ 8 13 17]]


# Multiplying two lists

In [9]:
lis1 = [1,2,3,4,5,6]
lis2 = [10,9,8,7,6,5]

a = np.array(lis1)
b = np.array(lis2)

print(a*b)

[10 18 24 28 30 30]


# Indexing

In [10]:
a = np.arange(10,1,-2)
print("A sequential array with negative steps: \n", a)

# newarr = a[([3, 1, 2])]
newarr = a[np.array([3, 1, 2])]
print("\n Elements at these indices are: \n", newarr)


A sequential array with negative steps: 
 [10  8  6  4  2]

 Elements at these indices are: 
 [4 8 6]


In [11]:
arr = np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])

temp = arr[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2): ", temp)

temp = arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3),(1,2),(2,1),(3, 0):\n", temp)

cond = arr>0
temp = arr[cond]
print("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternate columns(0 and 2):  [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0,3),(1,2),(2,1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# Negative Indexing

In [12]:
x = np.array([1,2,3,4,5,6,7,8,9])
arr = x[7]
print("\nElement is: \n", arr)
arr = x[np.array([7])]
print("\nElement is: \n", arr)
arr = x[np.array([1,3,-3])]
print("\nElements are: \n", arr)


Element is: 
 8

Element is: 
 [8]

Elements are: 
 [2 4 7]


# Iterating over an array

In [13]:
a = np.arange(12)

a = a.reshape(3,4)

print("Original array is: \n", a)
print("Modified arrary is :")
# for s in (a):
for s in np.nditer(a):
    print(s)

Original array is: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Modified arrary is :
0
1
2
3
4
5
6
7
8
9
10
11


In [14]:
a = np.arange(0,60,5) 
 
# shape array with 3 rows and 
# 4 columns 
a = a.reshape(3,4) 
 
print('Original array is:') 
print(a)
print()  
 
print('Modified array in F-style order:')
 
# iterating an array in a given
# order   
for x in np.nditer(a, order = 'F'): 
    print(x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

Modified array in F-style order:
0
20
40
5
25
45
10
30
50
15
35
55


In [15]:
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 5*x
print('Modified array is:')
print(a)

Modified array is:
[[  0  25  50  75]
 [100 125 150 175]
 [200 225 250 275]]


# Mathematical Function

In [16]:
import math
in_array = [0, math.pi/2, np.pi/3, np.pi]
print("Input array: \n", in_array)

cos_Values = np.cos(in_array)
print("\n Cosine Values:\n", cos_Values)

Input array: 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

 Cosine Values:
 [ 1.000000e+00  6.123234e-17  5.000000e-01 -1.000000e+00]


# String Operations

In [17]:
print(np.char.lower(["RUSHI", "ADI"]))

['rushi' 'adi']


In [18]:
print(np.char.split("Rushikesh sanjay pokharkar"))

['Rushikesh', 'sanjay', 'pokharkar']


In [19]:
print(np.char.join(["-","_"], ["Rushikesh", "Pokharkar"]))

['R-u-s-h-i-k-e-s-h' 'P_o_k_h_a_r_k_a_r']


In [20]:
# Liner Algebra Function: 
A = np.array([[6,1,1],
             [4,-2,5],
             [2,8,7]])
print("Rank of A: ", np.linalg.matrix_rank(A))
print("\nTrace of A: ", np.trace(A))
print("\nDeterminant of A: ", np.linalg.det(A))
print("\nInverse of A:\n", np.linalg.inv(A))
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A:  3

Trace of A:  11

Determinant of A:  -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [21]:
# Sorting 

a = np.array([[12, 15], 
              [10, 1]])
arr1 = np.sort(a, axis = 0)
print("Along first axis(Column): \n", arr1)

# sort along the last axis
a = np.array([[10, 15], 
              [12, 1]])
arr2 = np.sort(a, axis = 1)
print ("\nAlong first axis(Row) : \n", arr2)

a = np.array([[12, 15], 
              [10, 1]])
arr = np.sort(a, axis = None)
print("\nAlong none axis: \n", arr)


Along first axis(Column): 
 [[10  1]
 [12 15]]

Along first axis(Row) : 
 [[10 15]
 [ 1 12]]

Along none axis: 
 [ 1 10 12 15]


In [22]:
a = np.array([9, 3, 1, 7, 4, 3, 6])
 
# unsorted array print
print('Original array:\n', a)
 
# Sort array indices
b = np.argsort(a)
print('Sorted indices of original array->', b)
 
# To get sorted array using sorted indices
# c is temp array created of same len as of b
c = np.zeros(len(b), dtype = int)
for i in range(0, len(b)):
    c[i]= a[b[i]]
print('Sorted array->', c)

Original array:
 [9 3 1 7 4 3 6]
Sorted indices of original array-> [2 1 5 4 6 3 0]
Sorted array-> [1 3 3 4 6 7 9]


## Searching

In [23]:
array = np.arange(12).reshape(3, 4)
print("INPUT ARRAY : \n", array)
 
# No axis mentioned, so works on entire array
print("\nMax element : ", np.argmax(array))
 
# returning Indices of the max element
# as per the indices
print(("\nIndices of Max element : "
      , np.argmax(array, axis=0)))
print(("\nIndices of Max element : "
      , np.argmax(array, axis=1)))

INPUT ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Max element :  11
('\nIndices of Max element : ', array([2, 2, 2, 2], dtype=int64))
('\nIndices of Max element : ', array([3, 3, 3], dtype=int64))
